### ISSUE TITLE
1.0.2 android issue

### ISSUE THREAD

**Issue by xmorpher** [Tw1ddle/samcodes-admob#1]
Hi, 
when i use the version 1.0.2 fom this library i can't compile to android, 
## it says this in the output window:

-pre-compile:

-compile:
    [javac] Compiling 4 source files to D:\MyProject\bin\android\bin\deps\samcodes-admob\bin\classes
    [javac] warning: com\google\android\gms\ads\AdView.class(com\google\android\gms\ads:AdView.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    [javac] It is recommended that the compiler be upgraded.
    [javac] warning: com\google\android\gms\ads\InterstitialAd.class(com\google\android\gms\ads:InterstitialAd.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    [javac] It is recommended that the compiler be upgraded.
    [javac] warning: com\google\android\gms\ads\AdListener.class(com\google\android\gms\ads:AdListener.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    [javac] It is recommended that the compiler be upgraded.
    [javac] warning: com\google\android\gms\ads\AdRequest.class(com\google\android\gms\ads:AdRequest.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    [javac] It is recommended that the compiler be upgraded.
    [javac] warning: com\google\android\gms\ads\AdRequest$Builder.class(com\google\android\gms\ads:AdRequest$Builder.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    [javac] It is recommended that the compiler be upgraded.
    [javac] warning: com\google\android\gms\ads\AdSize.class(com\google\android\gms\ads:AdSize.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    [javac] It is recommended that the compiler be upgraded.
    [javac] D:\MyProject\bin\android\bin\deps\samcodes-admob\src\com\samcodes\admob\BannerListener.java:40: cannot find symbol
    [javac] symbol  : method getErrorReason(int)
    [javac] location: class com.samcodes.admob.AdMobExtension
    [javac]         Log.d(TAG, "onBannerFailedToLoad: " + AdMobExtension.getErrorReason(error));
    [javac]                                                             ^
    [javac] D:\MyProject\bin\android\bin\deps\samcodes-admob\src\com\samcodes\admob\InterstitialListener.java:40: cannot find symbol
    [javac] symbol  : method getErrorReason(int)
    [javac] location: class com.samcodes.admob.AdMobExtension
    [javac]         Log.d(TAG, "onInterstitialFailedToLoad: " + AdMobExtension.getErrorReason(error));
    [javac]                                                                   ^
    [javac] 2 errors
    [javac] 6 warnings

BUILD FAILED
C:\Development\Android_SDK\tools\ant\build.xml:597: The following error occurred while executing this line:
C:\Development\Android_SDK\tools\ant\build.xml:716: The following error occurred while executing this line:
## C:\Development\Android_SDK\tools\ant\build.xml:730: Compile failed; see the compiler error output for details.

When i set the library to 1.0.1 it compiles fine again... 
it seems to be something related to the versions of google play services and the "compiler"
(i'm using flashdevelop, haxe 3.2, the latests haxelib versions of lime/openfl, 
and google play services updated in the sdk)
i hope that helps, regards!

**Comment by Tw1ddle** [comment]
Thanks. I missed removing those getErrorReason calls, and also mistakenly tested the Chartboost haxelib instead of the AdMob one before submitting 1.0.2.

I just pushed the haxelib to 1.0.3, let me know if it's all working again.

**Comment by xmorpher** [comment]
Build succeeded!
:)
thanks
