### ISSUE TITLE
Update Android SDK to >7.0.0

### ISSUE THREAD

**Issue by xmorpher** [Tw1ddle/samcodes-admob#10]
I received a notification from Google saying the Android Admob SDK < 7.0.0 will be deprecated on January 23, 2018...
i'm not sure what SDK version use this extension for android, can anybody tell me?

If it's lower than 7.0.0 would it be possible to update it to use a compatible one so the extension won't be also deprecated?  

Thanks!

**Comment by Tw1ddle** [comment]
On Android I think it used whatever play services ads version you had installed when you build your app. 

Working on updating the haxelib now, looks like it works with the latest play services ads version on Android.
