### ISSUE TITLE
Problems with new haxe openfl and lime 

### ISSUE THREAD

**Issue by reaperspeeds** [Tw1ddle/samcodes-admob#11]
this is the error:
`...\bin\android\bin\deps\samcodes-admob\build\intermediates\bundles\release\aapt\AndroidManifest.xml:21:28-65: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')`

with the versions of:
`haxe 3.4.4
lime 6.1.0
openfl 7.1.1
`

can you tell what is it?

**Comment by Tw1ddle** [comment]
Not sure, probably an OpenFL compatibility issue. Likely be fixed in my next haxelib release that I'll release very soon.

If the problem persists, please fork this demo app and share a reproducible example, then I'll be able to diagnose the issue: https://github.com/Tw1ddle/samcodes-ads-demo
