### ISSUE TITLE
Suggestion (No issue) Samcodes-unityads

### ISSUE THREAD

**Issue by xmorpher** [Tw1ddle/samcodes-admob#5]
Your libraries are great, performs very well and are updated frequently...
Any chance of having "Samcodes-unityads" some day?
^_^

**Comment by Tw1ddle** [comment]
Hey, thanks for the praise. I don't use Unity at the moment, but it is on my (long) list of things to get into. So maybe in the future, but probably not this year. I'll let you know if I take it up.
