### ISSUE TITLE
Support for Admob Mediation

### ISSUE THREAD

**Issue by xmorpher** [Tw1ddle/samcodes-admob#6]
Hi,
i'm not sure if the extension supports Admob Mediation? 
(or has plans to support it in the future?)

**Comment by Tw1ddle** [comment]
I haven't taken steps to support the type of mediation where you add other network adapters/SDKs to an app. No immediate plans to look into that, but I might add it in the future.

AdMob has an SDK-less mediation option for a handful of networks, if that helps: https://admob.googleblog.com/2016/02/sdk-less-mediation.html

**Comment by xmorpher** [comment]
it does helps, thanks!

**Comment by Tw1ddle** [comment]
Great. Did the SDK-less mediation work well?

**Comment by xmorpher** [comment]
i have not tried the SDK-less option yet, sorry 
but i read about it and is a little limitated because it does not include the main ad networks...

**Comment by Tw1ddle** [comment]
I see, what networks were you looking to integrate?

I may look into how to add integrations for some of the networks that support ad network optimization: https://support.google.com/admob/answer/3379794?hl=en - I'm most interested in rewarded video. Not a high priority for me at present though.

**Comment by Tw1ddle** [comment]
I looked into this some more and decided not to implement mediation for this. I'd accept a PR though.
