### ISSUE TITLE
libAdMobAds.a missed

### ISSUE THREAD

**Issue by reaperspeeds** [Tw1ddle/samcodes-admob#7]
hi, i want to compile my project on ios, but i don't find the file libAdmobAds.a to built it.
In the extension folders I find libGoogleAdMobAds.a is that the same?... 
I used that file and I got this error:

 "_OBJC_CLASS_$_MFMessageComposeViewController", referenced from:
      objc-class-ref in libGoogleAdMobAds.a(flat-arm64)
  "_OBJC_CLASS_$_EKEventEditViewController", referenced from:
      objc-class-ref in libGoogleAdMobAds.a(flat-arm64)
  "_OBJC_CLASS_$_ASIdentifierManager", referenced from:
      objc-class-ref in libGoogleAdMobAds.a(flat-arm64)
      objc-class-ref in libGoogleAdMobAds.a(GADGestureIdUtil.o)
  "_OBJC_CLASS_$_MFMailComposeViewController", referenced from:
      objc-class-ref in libGoogleAdMobAds.a(flat-arm64)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any suggestion?

**Comment by Tw1ddle** [comment]
Hi, yes it is. Is libGoogleAdMobAds.a file showing in the "Link binary with libraries" section under the "Build Phases" tab in the generated Xcode project? Perhaps there are also some missing frameworks that need adding: MessageUI.framework, AdSupport.framework, EventKit/EventKitUI? You can add them manually, and I think you could drag-drop the .a file in if it's not there. Hope that helps.

I think there is a way for me to have those frameworks added/linked from one of the haxelib config files, but I haven't had chance to try that yet.

See: https://github.com/Tw1ddle/samcodes-admob/tree/master/project/include

**Comment by Tw1ddle** [comment]
Hey @reaperspeeds did the above help?

**Comment by reaperspeeds** [comment]
Yes, the  project compiled thanks :) ...
the charboost ad from your library showed but the admob ad is not showing... (on iOs)
(in android both libraries work as expected) any suggestion?

**Comment by Tw1ddle** [comment]
If you are using test ads, did you pass the hashed test device id in AdMob.init call for iOS? That's different step than on Android. Also, are there any errors in the console if you compile in debug mode and use it from Xcode? And what device and version of iOS are you using?

Let me know, and I will test this demo app on iOS next weekend and see what I find: https://github.com/Tw1ddle/samcodes-ads-demo

**Comment by reaperspeeds** [comment]
I don't know how to get my hashed test device, I leave it empty and I enter my strings of interestitial and banners in the demo and I get: 
 onInterestitialFailedToLoad...

I am using this libraries:
lime: 2.8.2
openfl : 3.5.3
flixel: 4.0.1
samcodes-admob: 1.0.8

I will keep trying...

**Comment by Tw1ddle** [comment]
I tested the samcodes-admob 1.0.8 haxelib using the demo app on iOS, iPad 2, deployment target iOS 5.1.1. The interstitials and banners are showing for me, with or without test ads.

Are you still having problems? There are many reasons an interstitial could fail to load. Which device and version of iOS were you using?

**Comment by reaperspeeds** [comment]
Hi
I'm using an Iphone 5 with iOs 9.3.2 
the android target works fine but the iOs version
still doesn't load interstitials

What openfl, lime and hxcpp library versions are you using?

**Comment by reaperspeeds** [comment]
here is my way to init Admob in my project:

```
#if ios
Admob.init();
AdMob.setListener(new AdMobListener());
#end
```

on iOs, in the xcode console i get this error: 
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadRewardedVideo]
and as far as i know, there are no rewarded videos on admob... 
but there are rewarded videos on samcodes-chartboost which i also using

is there a problem on iOs if you use samcodes-admob and samcodes-chartboost at the same time?
(on android they work fine together)

**Comment by Tw1ddle** [comment]
I have not tested using both extensions at the same time. Could you post a screenshot of that console output with the listener errors? Also, how are you initializing Chartboost?

I think AdMob does support rewarded video via mediation, though that's shouldn't apply here as I haven't added bindings for that.

**Comment by reaperspeeds** [comment]
![image](https://cloud.githubusercontent.com/assets/9083436/16750615/a1dba27c-4798-11e6-9bb1-b3c7c7ef649d.png)

It seems that the admob listener is getting the chartboost events on ios.

```

Warning : duplicate symbol set_listener__1
Warning : duplicate symbol show_interstitial__1
Warning : duplicate symbol cache_interstitial__1
Warning : duplicate symbol has_interstitial__1

AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didInitialize]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadRewardedVideo]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
PreguntaScene.hx:2408: visto video: false, video_disponible_continuar:false
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadRewardedVideo]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadRewardedVideo]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
PreguntaScene.hx:4618: ocultar ventana
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [shouldRequestInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadRewardedVideo]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]
AdMobListener.hx:119: Unhandled AdMob event. There shouldn't be any of these. Event type was [didFailToLoadInterstitial]

```

**Comment by Tw1ddle** [comment]
I see, this is because the CFFI defines in the libraries are clashing - in the code I have DEFINE_PRIM(set_listener, 1), which needs to be unique - like DEFINE_PRIM(samcodes_admob_set_listener, 1) - but isn't.

This is a nasty bug, I'll fix it soon and release new versions of the bindings. Thanks!

**Comment by Tw1ddle** [comment]
Alright, I updated the samcodes-admob and samcodes-chartboost haxelibs to try and fix the bug above. Hopefully no regressions, please let me know if it works for you!

**Comment by reaperspeeds** [comment]
it works! thanks. :)

**Comment by Tw1ddle** [comment]
That's great, let me know if you find any more problems :smile:
