### ISSUE TITLE
Class<openfl.Lib> has no field load

### ISSUE THREAD

**Issue by reaperspeeds** [Tw1ddle/samcodes-admob#9]
Hi, I tried to build my project with the last openfl and lime and I get this error.
/usr/local/lib/haxe/lib/samcodes-admob/1,0,9/extension/admob/AdMob.hx:75: characters 16-24 : Class<openfl.Lib> has no field load
/usr/local/lib/haxe/lib/samcodes-admob/1,0,9/extension/admob/AdMob.hx:95: characters 16-24 : Class<openfl.Lib> has no field load

Also happens with samcodes-chartboost. How I can fixed ?

my haxelib list is :

createjs: [1.5.8]
extension-android-support-v4: [1.0.0]
extension-googleplaygames: 1.3.2 1.3.3 1.4.0 1.5.0 [1.5.7]
extension-googleplayservices-basement: 1.0.2 [1.1.0]
extension-googleplayservices-lib: 1.1.0 [1.1.1]
extension-locale: 1.0.1 [1.0.3]
extension-share: 2.4.2 [2.4.3]
extension-youtubeplayer: [1.0.0]
gamecenter: [1.1.1]
haxe-ga: 0.5.2 [0.5.3]
haxelib_client: [3.2.0-rc.3]
HaxePunk: 2.5.6 [2.6.0]
hxcpp: 3.2.180 3.2.205 3.3.49 3.4.2 [3.4.49]
lime: 2.5.2 2.8.2 3.2.1 [3.7.4]
nape: [2.0.20]
openfl-gps-lib: [1.4.3]
openfl-unityads: 1.0.3 [1.0.7]
openfl: 3.2.2 3.5.3 [4.8.1]
samcodes-admob: 1.0.3 [1.0.9]
samcodes-chartboost: 1.0.1 1.0.5 1.0.6 [1.0.9]
samcodes-notifications: 1.0.1 1.0.4 [1.0.5]

**Comment by Tw1ddle** [comment]
Hi @reaperspeeds - looks like the same issue as #8, perhaps a breaking change in the latest version of OpenFL (I cannot see anything in their changelog though).

I do not have time to update the haxelibs just at the moment. I certainly will do once OpenFL 4.x support is added to HaxeFlixel, since that is what my test app uses: https://github.com/Tw1ddle/samcodes-ads-demo

**Comment by reaperspeeds** [comment]
Hi i made a test with only openfl doing the calling to the functions in AdWrapper, perhaps this could help you to find the error quickly :)
[blank_test.zip](https://github.com/Tw1ddle/samcodes-admob/files/842338/blank_test.zip)

**Comment by Tw1ddle** [comment]
Thanks for that - I don't have my Mac set up at the moment, but looking around it looks like the same as this: https://github.com/openfl/extension-iap/issues/44

If that's the problem, then replacing flash.Lib import in AdMob.hx with lime.system.CFFI should be a workaround until I find time to update the haxelib (I will get around to this soon).

**Comment by reaperspeeds** [comment]
Thats works fine for my with the two libraries and i have another problems with openfl.Lib but for another library that use Lib.pause and i dont find the error :/ or how to fix this

**Comment by Tw1ddle** [comment]
I'm working on updating the haxelib and demo app now that OpenFL 8 support has been added to HaxeFlixel, this will be fixed in the next haxelib release.
